services:
  - type: web
    name: tatu-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true 